name: AllAndOnlyChests
version: '1.0-SNAPSHOT'
main: dev.skippaddin.allAndOnlyChests.AllAndOnlyChests
api-version: '1.21'
commands:
  structures:
    description: Shows all unfinished and finished structures. Select your structure here.
    permissions: AllAndOnlyChests.command.structures
    default: op
  structure:
    description: Commands related to a single structure
    permissions:
      AllAndOnlyChests.command.finish:
        description: "Completes the current selected structure."